In [12]:
import numpy as np

class ArrayCreator:
    def create_1d(self):
        data = np.array(list(map(float, input("Enter elements separated by space: ").split())))
        print("Array created:", data)
        return data

    def create_2d(self):
        rows = int(input("Enter number of rows: "))
        print("Enter each row separated by spaces:")
        matrix = []
        for i in range(rows):
            row = list(map(float, input(f"Row {i+1}: ").split()))
            matrix.append(row)
        arr = np.array(matrix)
        print("Array created:\n", arr)
        return arr

    def create_3d(self):
        layers = int(input("Enter number of layers: "))
        rows = int(input("Enter number of rows per layer: "))
        print("Enter data layer-wise and row-wise separated by spaces:")
        data = []
        for i in range(layers):
            layer = []
            print(f"Layer {i+1}:")
            for j in range(rows):
                row = list(map(float, input(f"Row {j+1}: ").split()))
                layer.append(row)
            data.append(layer)
        arr = np.array(data)
        print("Array created:\n", arr)
        return arr

class ArrayOperations:
    def statistics(self, arr):
        print("Choose an aggregate/statistical operation:")
        print("1.Sum")
        print("2.Mean")
        print("3.Median")
        print("4.Standard Deviation")
        print("5.Variance")
    
        ch = int(input("Enter your choice: "))
    
        print("\nOriginal Array:")
        print(arr)
    
        if ch == 1:
            print("Sum:", np.sum(arr))
        elif ch == 2:
            print("Mean:", np.mean(arr))
        elif ch == 3:
            print("Median:", np.median(arr))
        elif ch == 4:
            print("Standard Deviation:", np.std(arr))
        elif ch == 5:
            print("Variance:", np.var(arr))
        else:
            print("Invalid choice!")

    
    def search_sort_filter(self, arr):
        print("Choose an option:")
        print("1.Search a value")
        print("2.Sort the array")
        print("3.Filter values")
        ch = int(input("Enter your choice: "))

        if ch == 1:
            val = float(input("Enter value to search: "))
            result = np.where(arr == val)

            coords = list(zip(*result))
            if coords:
                for c in coords:
                    clean_index = tuple(int(i) for i in c)
                    print("Value found at index", clean_index)
            else:
                print("Value not found")


        elif ch == 2:
            if arr.ndim == 1:
                print("Sorted array:", np.sort(arr))
            elif arr.ndim == 2:
                print("Sorted array:\n", np.sort(arr, axis=1))
            elif arr.ndim == 3:
                print("Sorted array:\n", np.sort(arr, axis=2))

        elif ch == 3:
            print("1.Greater than")
            print("2.Less than")
            print("3.Equal to")
            f = int(input("Choose filter type: "))
            val = float(input("Enter value: "))

            if f == 1:
                print("Filtered array:\n", arr[arr > val])
            elif f == 2:
                print("Filtered array:\n", arr[arr < val])
            elif f == 3:
                print("Filtered array:\n", arr[arr == val])

    def array_menu(self, arr):
        while True:
            print("\nChoose an operation:")
            print("1.Indexing")
            print("2.Slicing")
            print("3.Go back")
            ch = int(input("Enter choice: "))

            if ch == 1:
                print("Enter indices separated by commas (ex: 1 or 1,2):")
                idx = tuple(map(int, input("Index: ").split(",")))
                print("Indexed value:", arr[idx])

            elif ch == 2:
                print("Enter ranges as start:end format (leave blank for full range)")

                row_range = input("Enter row range (start:end): ")
                col_range = None
                depth_range = None

                if arr.ndim >= 2:
                    col_range = input("Enter column range (start:end): ")

                if arr.ndim == 3:
                    depth_range = input("Enter depth range (start:end): ")

                def convert(r):
                    if r == "":
                        return slice(None)
                    parts = r.split(":")
                    return slice(int(parts[0]) if parts[0] else None,
                                 int(parts[1]) if parts[1] else None)

                r = convert(row_range)

                if arr.ndim == 1:
                    print("Sliced array:", arr[r])

                elif arr.ndim == 2:
                    c = convert(col_range)
                    print("Sliced array:\n", arr[r, c])

                elif arr.ndim == 3:
                    d = convert(depth_range)
                    print("Sliced array:\n", arr[r, c, d])

            elif ch == 3:
                break


    def math_operation(self, arr):
        print("Enter second array")
        creator = ArrayCreator()
        type_choice = int(input("Choose type: 1D=1, 2D=2, 3D=3: "))

        if type_choice == 1:
            arr2 = creator.create_1d()
        elif type_choice == 2:
            arr2 = creator.create_2d()
        else:
            arr2 = creator.create_3d()

        print("Select operation:")
        print("1.Addition")
        print("2.Subtraction")
        print("3.Multiplication")
        op = int(input("Enter choice: "))

        if op == 1:
            print("Result:\n", arr + arr2)
        elif op == 2:
            print("Result:\n", arr - arr2)
        elif op == 3:
            print("Result:\n", arr * arr2)

    def combine_or_split(self, arr):
        print("Choose an option:")
        print("1.Combine arrays")
        print("2.Split array")
        ch = int(input("Enter choice: "))

        if ch == 1:
            creator = ArrayCreator()
            print("Create second array to combine:")
            type_choice = int(input("Choose type: 1D=1, 2D=2, 3D=3: "))

            if type_choice == 1:
                arr2 = creator.create_1d()
            elif type_choice == 2:
                arr2 = creator.create_2d()
            else:
                arr2 = creator.create_3d()

            print("Choose combine axis:")
            print("0.Axis 0")
            print("1.Axis 1 (if valid)")
            axis = int(input("Enter axis: "))
            print("Combined:\n", np.concatenate((arr, arr2), axis=axis))

        elif ch == 2:
            print("Choose split method:")
            print("1.Split into equal parts")
            print("2.Split at custom index")

            s = int(input("Enter choice: "))
            if s == 1:
                n = int(input("Enter number of splits: "))
                print("Result:\n", np.array_split(arr, n))
            elif s == 2:
                idx = list(map(int, input("Enter split indices separated by space: ").split()))
                print("Result:\n", np.split(arr, idx))



creator = ArrayCreator()
ops = ArrayOperations()

print("Welcome to the NumPy analyzer!")
print("=====================================")

arr = None

while True:
    print("\nChoose an option:")
    print("1.Create a numpy array")
    print("2.Perform mathematical operations")
    print("3.Combine or Split Arrays")
    print("4.Search,sort or filter arrays")
    print("5.Compute aggregates and Statisticts")
    print("6.Exit")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("Select an array type to create:")
        print("1. 1D array")
        print("2. 2D array")
        print("3. 3D array")
        a_type = int(input("Enter your choice: "))

        if a_type == 1:
            arr = creator.create_1d()
            ops.array_menu(arr)

        elif a_type == 2:
            arr = creator.create_2d()
            ops.array_menu(arr)

        elif a_type == 3:
            arr = creator.create_3d()
            ops.array_menu(arr)

    if choice == 2:
        if arr is None:
            print("No array created yet!")
        else:
            ops.math_operation(arr)

    if choice == 3:
        if arr is None:
            print("No array created yet!")
        else:
            ops.combine_or_split(arr)
    if choice == 4:
        if arr is None:
            print("No array created yet!")
        else:
            ops.search_sort_filter(arr)
    if choice ==5:
        if arr is None:
            print("No array created yet!")
        else:
            ops.statistics(arr)
    if choice == 6:
        print("Thank you for using Nummpy analyzer! Goodbye!")
        break


Welcome to the NumPy analyzer!

Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  1


Select an array type to create:
1. 1D array
2. 2D array
3. 3D array


Enter your choice:  2
Enter number of rows:  2


Enter each row separated by spaces:


Row 1:  2 1 34 2
Row 2:  2 1 4 2


Array created:
 [[ 2.  1. 34.  2.]
 [ 2.  1.  4.  2.]]

Choose an operation:
1.Indexing
2.Slicing
3.Go back


Enter choice:  3



Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  5


Choose an aggregate/statistical operation:
1.Sum
2.Mean
3.Median
4.Standard Deviation
5.Variance


Enter your choice:  1



Original Array:
[[ 2.  1. 34.  2.]
 [ 2.  1.  4.  2.]]
Sum: 48.0

Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  5


Choose an aggregate/statistical operation:
1.Sum
2.Mean
3.Median
4.Standard Deviation
5.Variance


Enter your choice:  2



Original Array:
[[ 2.  1. 34.  2.]
 [ 2.  1.  4.  2.]]
Mean: 6.0

Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  5


Choose an aggregate/statistical operation:
1.Sum
2.Mean
3.Median
4.Standard Deviation
5.Variance


Enter your choice:  3



Original Array:
[[ 2.  1. 34.  2.]
 [ 2.  1.  4.  2.]]
Median: 2.0

Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  5


Choose an aggregate/statistical operation:
1.Sum
2.Mean
3.Median
4.Standard Deviation
5.Variance


Enter your choice:  5



Original Array:
[[ 2.  1. 34.  2.]
 [ 2.  1.  4.  2.]]
Variance: 112.75

Choose an option:
1.Create a numpy array
2.Perform mathematical operations
3.Combine or Split Arrays
4.Search,sort or filter arrays
5.Compute aggregates and Statisticts
6.Exit


Enter your choice:  6
